// // categories and their sub-categories
// final Map<String, List<String>> categoryMap = {
//   'Nyaa': [
//     'AllCategories',
//     'Anime',
//     'AnimeMusicVideo',
//     'AnimeEnglishTranslated',
//     'AnimeNonEnglishTranslated',
//     'AnimeRaw',
//     'Audio',
//     'AudioLossLess',
//     'AudioLossy',
//     'Literature',
//     'LiteratureEnglishTranslated',
//     'LiteratureNonEnglishTranslated',
//     'LiteratureRaw',
//     'LiveAction',
//     'LiveActionEnglishTranslated',
//     'LiveActionNonEnglishTranslated',
//     'LiveActionIdolePromotionalVideo',
//     'LiveActionRaw',
//     'Pictures',
//     'PicturesGraphics',
//     'PicturesPhotos',
//     'Software',
//     'SoftwareApplications',
//     'SoftwareGames',
//   ],
//   'Nyaa [Sukebei]': ['Action', 'Comedy', 'Horror', 'Sci-Fi'],
//   'LimeTorrent': ['Drama', 'Comedy', 'Animated'],
// };
