// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/app.dart';
import 'api/database/bookmark.dart';
import 'api/database/get_settings_kv.dart';
import 'api/database/initialize.dart';
import 'api/database/proxy.dart';
import 'api/internals.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1540046324;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_torrents_digger',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<BigInt> crateApiDatabaseBookmarkBookmarkATorrent({
    required InternalTorrent torrent,
    required int categoryId,
  });

  Future<void> crateApiDatabaseBookmarkChangeBookmarkCategory({
    required String infoHash,
    required int categoryId,
  });

  Future<int> crateApiAppCheckNewUpdate();

  Future<void> crateApiDatabaseBookmarkCreateBookmarkCategory({
    required String categoryName,
  });

  Future<void> crateApiDatabaseBookmarkDeleteBookmarkCategory({
    required int categoryId,
  });

  Future<BigInt> crateApiDatabaseProxyDeleteProxy({required int proxyId});

  Future<(List<InternalTorrent>, InternalPagination)>
  crateApiAppDigCustomTorrents({
    required BigInt selectedSourceIndex,
    required BigInt selectedListingIndex,
  });

  Future<(List<InternalTorrent>, InternalPagination)> crateApiAppDigTorrent({
    required String torrentName,
    required BigInt sourceIndex,
    required BigInt categoryIndex,
    required BigInt filterIndex,
    required BigInt sortingIndex,
    required BigInt sortingOrderIndex,
    PlatformInt64? page,
  });

  Future<List<InternalSource>> crateApiAppFetchSourceDetails();

  Future<String?> crateApiDatabaseGetSettingsKvGetASettingsKv({
    required String key,
  });

  Future<String?> crateApiDatabaseGetSettingsKvGetActiveCustomDnsResolver();

  Future<String> crateApiDatabaseGetSettingsKvGetActiveDefaultTrackersList();

  Future<List<(BigInt, String)>> crateApiAppGetAllDefaultTrackersList();

  Future<Set<String>> crateApiDatabaseBookmarkGetAllInfoHashes();

  Future<String> crateApiAppGetAppCurrentVersion();

  Future<List<InternalTorrent>> crateApiDatabaseBookmarkGetBookmarks({
    required int categoryId,
  });

  Future<InternalBookmarksStats> crateApiAppGetBookmarksStats();

  Future<List<InternalBookmarkCategory>>
  crateApiDatabaseBookmarkGetCategories();

  Future<List<InternalCustomDNS>> crateApiAppGetCustomDnsLists();

  Future<List<InternalCustomSourceDetails>> crateApiAppGetCustomsDetails();

  Future<String> crateApiAppGetIpDetails();

  Future<String> crateApiAppGetProcessedMagnetLink({
    required String unprocessedMagnet,
  });

  Future<InternalProxy?> crateApiDatabaseProxyGetSavedProxy();

  Future<Map<String, String>> crateApiDatabaseGetSettingsKvGetSettingsKv();

  Future<List<(int, String)>> crateApiDatabaseProxyGetSupportedProxyDetails();

  Future<void> crateApiDatabaseInitializeInitializeTorrentsDiggerDatabase({
    required String torrentsDiggerDatabaseDirectory,
  });

  Future<String> crateApiDatabaseGetSettingsKvInsertOrUpdateKv({
    required String key,
    required String value,
  });

  Future<bool> crateApiAppLoadDefaultTrackersString();

  Future<void> crateApiDatabaseInitializeMigrateDatabaseToLatest();

  Future<bool> crateApiDatabaseBookmarkRemoveBookmark({
    required String infoHash,
  });

  Future<void> crateApiDatabaseBookmarkRenameBookmarkCategory({
    required int categoryId,
    required String oldCategoryName,
    required String newCategoryName,
  });

  Future<BigInt> crateApiDatabaseProxySaveProxyApi({
    required InternalProxy proxyData,
  });

  Future<BigInt> crateApiDatabaseGetSettingsKvSetActiveCustomDnsResolver({
    required int index,
  });

  Future<BigInt> crateApiDatabaseGetSettingsKvSetDefaultTrackersList({
    required int index,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<BigInt> crateApiDatabaseBookmarkBookmarkATorrent({
    required InternalTorrent torrent,
    required int categoryId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_internal_torrent(torrent, serializer);
          sse_encode_u_8(categoryId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseBookmarkBookmarkATorrentConstMeta,
        argValues: [torrent, categoryId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseBookmarkBookmarkATorrentConstMeta =>
      const TaskConstMeta(
        debugName: "bookmark_a_torrent",
        argNames: ["torrent", "categoryId"],
      );

  @override
  Future<void> crateApiDatabaseBookmarkChangeBookmarkCategory({
    required String infoHash,
    required int categoryId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(infoHash, serializer);
          sse_encode_u_8(categoryId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseBookmarkChangeBookmarkCategoryConstMeta,
        argValues: [infoHash, categoryId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseBookmarkChangeBookmarkCategoryConstMeta =>
      const TaskConstMeta(
        debugName: "change_bookmark_category",
        argNames: ["infoHash", "categoryId"],
      );

  @override
  Future<int> crateApiAppCheckNewUpdate() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppCheckNewUpdateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppCheckNewUpdateConstMeta =>
      const TaskConstMeta(debugName: "check_new_update", argNames: []);

  @override
  Future<void> crateApiDatabaseBookmarkCreateBookmarkCategory({
    required String categoryName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(categoryName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseBookmarkCreateBookmarkCategoryConstMeta,
        argValues: [categoryName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseBookmarkCreateBookmarkCategoryConstMeta =>
      const TaskConstMeta(
        debugName: "create_bookmark_category",
        argNames: ["categoryName"],
      );

  @override
  Future<void> crateApiDatabaseBookmarkDeleteBookmarkCategory({
    required int categoryId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8(categoryId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseBookmarkDeleteBookmarkCategoryConstMeta,
        argValues: [categoryId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseBookmarkDeleteBookmarkCategoryConstMeta =>
      const TaskConstMeta(
        debugName: "delete_bookmark_category",
        argNames: ["categoryId"],
      );

  @override
  Future<BigInt> crateApiDatabaseProxyDeleteProxy({required int proxyId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(proxyId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseProxyDeleteProxyConstMeta,
        argValues: [proxyId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseProxyDeleteProxyConstMeta =>
      const TaskConstMeta(debugName: "delete_proxy", argNames: ["proxyId"]);

  @override
  Future<(List<InternalTorrent>, InternalPagination)>
  crateApiAppDigCustomTorrents({
    required BigInt selectedSourceIndex,
    required BigInt selectedListingIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_usize(selectedSourceIndex, serializer);
          sse_encode_usize(selectedListingIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_record_list_internal_torrent_internal_pagination,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppDigCustomTorrentsConstMeta,
        argValues: [selectedSourceIndex, selectedListingIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppDigCustomTorrentsConstMeta =>
      const TaskConstMeta(
        debugName: "dig_custom_torrents",
        argNames: ["selectedSourceIndex", "selectedListingIndex"],
      );

  @override
  Future<(List<InternalTorrent>, InternalPagination)> crateApiAppDigTorrent({
    required String torrentName,
    required BigInt sourceIndex,
    required BigInt categoryIndex,
    required BigInt filterIndex,
    required BigInt sortingIndex,
    required BigInt sortingOrderIndex,
    PlatformInt64? page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(torrentName, serializer);
          sse_encode_usize(sourceIndex, serializer);
          sse_encode_usize(categoryIndex, serializer);
          sse_encode_usize(filterIndex, serializer);
          sse_encode_usize(sortingIndex, serializer);
          sse_encode_usize(sortingOrderIndex, serializer);
          sse_encode_opt_box_autoadd_i_64(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_record_list_internal_torrent_internal_pagination,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppDigTorrentConstMeta,
        argValues: [
          torrentName,
          sourceIndex,
          categoryIndex,
          filterIndex,
          sortingIndex,
          sortingOrderIndex,
          page,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppDigTorrentConstMeta => const TaskConstMeta(
    debugName: "dig_torrent",
    argNames: [
      "torrentName",
      "sourceIndex",
      "categoryIndex",
      "filterIndex",
      "sortingIndex",
      "sortingOrderIndex",
      "page",
    ],
  );

  @override
  Future<List<InternalSource>> crateApiAppFetchSourceDetails() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_internal_source,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppFetchSourceDetailsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppFetchSourceDetailsConstMeta =>
      const TaskConstMeta(debugName: "fetch_source_details", argNames: []);

  @override
  Future<String?> crateApiDatabaseGetSettingsKvGetASettingsKv({
    required String key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseGetSettingsKvGetASettingsKvConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseGetSettingsKvGetASettingsKvConstMeta =>
      const TaskConstMeta(debugName: "get_a_settings_kv", argNames: ["key"]);

  @override
  Future<String?> crateApiDatabaseGetSettingsKvGetActiveCustomDnsResolver() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiDatabaseGetSettingsKvGetActiveCustomDnsResolverConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDatabaseGetSettingsKvGetActiveCustomDnsResolverConstMeta =>
      const TaskConstMeta(
        debugName: "get_active_custom_dns_resolver",
        argNames: [],
      );

  @override
  Future<String> crateApiDatabaseGetSettingsKvGetActiveDefaultTrackersList() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiDatabaseGetSettingsKvGetActiveDefaultTrackersListConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDatabaseGetSettingsKvGetActiveDefaultTrackersListConstMeta =>
      const TaskConstMeta(
        debugName: "get_active_default_trackers_list",
        argNames: [],
      );

  @override
  Future<List<(BigInt, String)>> crateApiAppGetAllDefaultTrackersList() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_record_usize_string,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppGetAllDefaultTrackersListConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppGetAllDefaultTrackersListConstMeta =>
      const TaskConstMeta(
        debugName: "get_all_default_trackers_list",
        argNames: [],
      );

  @override
  Future<Set<String>> crateApiDatabaseBookmarkGetAllInfoHashes() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_Set_String_None,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseBookmarkGetAllInfoHashesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseBookmarkGetAllInfoHashesConstMeta =>
      const TaskConstMeta(debugName: "get_all_info_hashes", argNames: []);

  @override
  Future<String> crateApiAppGetAppCurrentVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppGetAppCurrentVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppGetAppCurrentVersionConstMeta =>
      const TaskConstMeta(debugName: "get_app_current_version", argNames: []);

  @override
  Future<List<InternalTorrent>> crateApiDatabaseBookmarkGetBookmarks({
    required int categoryId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8(categoryId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_internal_torrent,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseBookmarkGetBookmarksConstMeta,
        argValues: [categoryId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseBookmarkGetBookmarksConstMeta =>
      const TaskConstMeta(debugName: "get_bookmarks", argNames: ["categoryId"]);

  @override
  Future<InternalBookmarksStats> crateApiAppGetBookmarksStats() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_internal_bookmarks_stats,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppGetBookmarksStatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppGetBookmarksStatsConstMeta =>
      const TaskConstMeta(debugName: "get_bookmarks_stats", argNames: []);

  @override
  Future<List<InternalBookmarkCategory>>
  crateApiDatabaseBookmarkGetCategories() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_internal_bookmark_category,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseBookmarkGetCategoriesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseBookmarkGetCategoriesConstMeta =>
      const TaskConstMeta(debugName: "get_categories", argNames: []);

  @override
  Future<List<InternalCustomDNS>> crateApiAppGetCustomDnsLists() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_internal_custom_dns,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppGetCustomDnsListsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppGetCustomDnsListsConstMeta =>
      const TaskConstMeta(debugName: "get_custom_dns_lists", argNames: []);

  @override
  Future<List<InternalCustomSourceDetails>> crateApiAppGetCustomsDetails() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_internal_custom_source_details,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppGetCustomsDetailsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppGetCustomsDetailsConstMeta =>
      const TaskConstMeta(debugName: "get_customs_details", argNames: []);

  @override
  Future<String> crateApiAppGetIpDetails() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppGetIpDetailsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppGetIpDetailsConstMeta =>
      const TaskConstMeta(debugName: "get_ip_details", argNames: []);

  @override
  Future<String> crateApiAppGetProcessedMagnetLink({
    required String unprocessedMagnet,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(unprocessedMagnet, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppGetProcessedMagnetLinkConstMeta,
        argValues: [unprocessedMagnet],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppGetProcessedMagnetLinkConstMeta =>
      const TaskConstMeta(
        debugName: "get_processed_magnet_link",
        argNames: ["unprocessedMagnet"],
      );

  @override
  Future<InternalProxy?> crateApiDatabaseProxyGetSavedProxy() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_internal_proxy,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseProxyGetSavedProxyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseProxyGetSavedProxyConstMeta =>
      const TaskConstMeta(debugName: "get_saved_proxy", argNames: []);

  @override
  Future<Map<String, String>> crateApiDatabaseGetSettingsKvGetSettingsKv() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_Map_String_String_None,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseGetSettingsKvGetSettingsKvConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseGetSettingsKvGetSettingsKvConstMeta =>
      const TaskConstMeta(debugName: "get_settings_kv", argNames: []);

  @override
  Future<List<(int, String)>> crateApiDatabaseProxyGetSupportedProxyDetails() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_record_i_32_string,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDatabaseProxyGetSupportedProxyDetailsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseProxyGetSupportedProxyDetailsConstMeta =>
      const TaskConstMeta(
        debugName: "get_supported_proxy_details",
        argNames: [],
      );

  @override
  Future<void> crateApiDatabaseInitializeInitializeTorrentsDiggerDatabase({
    required String torrentsDiggerDatabaseDirectory,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(torrentsDiggerDatabaseDirectory, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiDatabaseInitializeInitializeTorrentsDiggerDatabaseConstMeta,
        argValues: [torrentsDiggerDatabaseDirectory],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDatabaseInitializeInitializeTorrentsDiggerDatabaseConstMeta =>
      const TaskConstMeta(
        debugName: "initialize_torrents_digger_database",
        argNames: ["torrentsDiggerDatabaseDirectory"],
      );

  @override
  Future<String> crateApiDatabaseGetSettingsKvInsertOrUpdateKv({
    required String key,
    required String value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_String(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseGetSettingsKvInsertOrUpdateKvConstMeta,
        argValues: [key, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseGetSettingsKvInsertOrUpdateKvConstMeta =>
      const TaskConstMeta(
        debugName: "insert_or_update_kv",
        argNames: ["key", "value"],
      );

  @override
  Future<bool> crateApiAppLoadDefaultTrackersString() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppLoadDefaultTrackersStringConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppLoadDefaultTrackersStringConstMeta =>
      const TaskConstMeta(
        debugName: "load_default_trackers_string",
        argNames: [],
      );

  @override
  Future<void> crateApiDatabaseInitializeMigrateDatabaseToLatest() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseInitializeMigrateDatabaseToLatestConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDatabaseInitializeMigrateDatabaseToLatestConstMeta =>
      const TaskConstMeta(
        debugName: "migrate_database_to_latest",
        argNames: [],
      );

  @override
  Future<bool> crateApiDatabaseBookmarkRemoveBookmark({
    required String infoHash,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(infoHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseBookmarkRemoveBookmarkConstMeta,
        argValues: [infoHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseBookmarkRemoveBookmarkConstMeta =>
      const TaskConstMeta(debugName: "remove_bookmark", argNames: ["infoHash"]);

  @override
  Future<void> crateApiDatabaseBookmarkRenameBookmarkCategory({
    required int categoryId,
    required String oldCategoryName,
    required String newCategoryName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8(categoryId, serializer);
          sse_encode_String(oldCategoryName, serializer);
          sse_encode_String(newCategoryName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseBookmarkRenameBookmarkCategoryConstMeta,
        argValues: [categoryId, oldCategoryName, newCategoryName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseBookmarkRenameBookmarkCategoryConstMeta =>
      const TaskConstMeta(
        debugName: "rename_bookmark_category",
        argNames: ["categoryId", "oldCategoryName", "newCategoryName"],
      );

  @override
  Future<BigInt> crateApiDatabaseProxySaveProxyApi({
    required InternalProxy proxyData,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_internal_proxy(proxyData, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseProxySaveProxyApiConstMeta,
        argValues: [proxyData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseProxySaveProxyApiConstMeta =>
      const TaskConstMeta(debugName: "save_proxy_api", argNames: ["proxyData"]);

  @override
  Future<BigInt> crateApiDatabaseGetSettingsKvSetActiveCustomDnsResolver({
    required int index,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_8(index, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiDatabaseGetSettingsKvSetActiveCustomDnsResolverConstMeta,
        argValues: [index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDatabaseGetSettingsKvSetActiveCustomDnsResolverConstMeta =>
      const TaskConstMeta(
        debugName: "set_active_custom_dns_resolver",
        argNames: ["index"],
      );

  @override
  Future<BigInt> crateApiDatabaseGetSettingsKvSetDefaultTrackersList({
    required int index,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_8(index, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiDatabaseGetSettingsKvSetDefaultTrackersListConstMeta,
        argValues: [index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDatabaseGetSettingsKvSetDefaultTrackersListConstMeta =>
      const TaskConstMeta(
        debugName: "set_default_trackers_list",
        argNames: ["index"],
      );

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  Set<String> dco_decode_Set_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Set.from(dco_decode_list_String(raw));
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  InternalProxy dco_decode_box_autoadd_internal_proxy(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_internal_proxy(raw);
  }

  @protected
  InternalTorrent dco_decode_box_autoadd_internal_torrent(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_internal_torrent(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  int dco_decode_i_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  InternalBookmarkCategory dco_decode_internal_bookmark_category(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return InternalBookmarkCategory(
      id: dco_decode_u_16(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  InternalBookmarksStats dco_decode_internal_bookmarks_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return InternalBookmarksStats(
      categoriesStats: dco_decode_list_internal_category_stats(arr[0]),
      globalStats: dco_decode_internal_global_stats(arr[1]),
    );
  }

  @protected
  InternalCategoryStats dco_decode_internal_category_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return InternalCategoryStats(
      category: dco_decode_internal_bookmark_category(arr[0]),
      categoryTotalCount: dco_decode_u_16(arr[1]),
      categoryTotalSize: dco_decode_String(arr[2]),
    );
  }

  @protected
  InternalCustomDNS dco_decode_internal_custom_dns(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return InternalCustomDNS(
      index: dco_decode_usize(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  InternalCustomSourceDetails dco_decode_internal_custom_source_details(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return InternalCustomSourceDetails(
      customSourceName: dco_decode_String(arr[0]),
      customSourceListings: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  InternalGlobalStats dco_decode_internal_global_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return InternalGlobalStats(
      totalTorrentsCount: dco_decode_u_32(arr[0]),
      totalTorrentsSize: dco_decode_String(arr[1]),
    );
  }

  @protected
  InternalPagination dco_decode_internal_pagination(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return InternalPagination(
      previousPage: dco_decode_opt_box_autoadd_i_32(arr[0]),
      currentPage: dco_decode_opt_box_autoadd_i_32(arr[1]),
      nextPage: dco_decode_opt_box_autoadd_i_32(arr[2]),
    );
  }

  @protected
  InternalProxy dco_decode_internal_proxy(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return InternalProxy(
      id: dco_decode_i_32(arr[0]),
      proxyName: dco_decode_String(arr[1]),
      proxyType: dco_decode_String(arr[2]),
      proxyServerIp: dco_decode_String(arr[3]),
      proxyServerPort: dco_decode_String(arr[4]),
      proxyUsername: dco_decode_opt_String(arr[5]),
      proxyPassword: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  InternalQueryOptions dco_decode_internal_query_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return InternalQueryOptions(
      categories: dco_decode_bool(arr[0]),
      filters: dco_decode_bool(arr[1]),
      sortings: dco_decode_bool(arr[2]),
      sortingOrders: dco_decode_bool(arr[3]),
      pagination: dco_decode_bool(arr[4]),
    );
  }

  @protected
  InternalSource dco_decode_internal_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return InternalSource(
      sourceName: dco_decode_String(arr[0]),
      sourceDetails: dco_decode_internal_source_details(arr[1]),
    );
  }

  @protected
  InternalSourceDetails dco_decode_internal_source_details(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return InternalSourceDetails(
      queryOptions: dco_decode_internal_query_options(arr[0]),
      categories: dco_decode_list_String(arr[1]),
      sourceFilters: dco_decode_list_String(arr[2]),
      sourceSortings: dco_decode_list_String(arr[3]),
      sourceSortingOrders: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  InternalTorrent dco_decode_internal_torrent(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return InternalTorrent(
      infoHash: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      magnet: dco_decode_String(arr[2]),
      size: dco_decode_String(arr[3]),
      date: dco_decode_String(arr[4]),
      seeders: dco_decode_String(arr[5]),
      leechers: dco_decode_String(arr[6]),
      totalDownloads: dco_decode_String(arr[7]),
      sourceUrl: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<InternalBookmarkCategory> dco_decode_list_internal_bookmark_category(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_internal_bookmark_category)
        .toList();
  }

  @protected
  List<InternalCategoryStats> dco_decode_list_internal_category_stats(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_internal_category_stats)
        .toList();
  }

  @protected
  List<InternalCustomDNS> dco_decode_list_internal_custom_dns(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_internal_custom_dns).toList();
  }

  @protected
  List<InternalCustomSourceDetails>
  dco_decode_list_internal_custom_source_details(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_internal_custom_source_details)
        .toList();
  }

  @protected
  List<InternalSource> dco_decode_list_internal_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_internal_source).toList();
  }

  @protected
  List<InternalTorrent> dco_decode_list_internal_torrent(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_internal_torrent).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(int, String)> dco_decode_list_record_i_32_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_i_32_string).toList();
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  List<(BigInt, String)> dco_decode_list_record_usize_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_usize_string).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  InternalProxy? dco_decode_opt_box_autoadd_internal_proxy(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_internal_proxy(raw);
  }

  @protected
  (int, String) dco_decode_record_i_32_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_i_32(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  (List<InternalTorrent>, InternalPagination)
  dco_decode_record_list_internal_torrent_internal_pagination(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_list_internal_torrent(arr[0]),
      dco_decode_internal_pagination(arr[1]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  (BigInt, String) dco_decode_record_usize_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_usize(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  Set<String> sse_decode_Set_String_None(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_String(deserializer);
    return Set.from(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  InternalProxy sse_decode_box_autoadd_internal_proxy(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_internal_proxy(deserializer));
  }

  @protected
  InternalTorrent sse_decode_box_autoadd_internal_torrent(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_internal_torrent(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  int sse_decode_i_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt8();
  }

  @protected
  InternalBookmarkCategory sse_decode_internal_bookmark_category(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_16(deserializer);
    var var_name = sse_decode_String(deserializer);
    return InternalBookmarkCategory(id: var_id, name: var_name);
  }

  @protected
  InternalBookmarksStats sse_decode_internal_bookmarks_stats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_categoriesStats = sse_decode_list_internal_category_stats(
      deserializer,
    );
    var var_globalStats = sse_decode_internal_global_stats(deserializer);
    return InternalBookmarksStats(
      categoriesStats: var_categoriesStats,
      globalStats: var_globalStats,
    );
  }

  @protected
  InternalCategoryStats sse_decode_internal_category_stats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_category = sse_decode_internal_bookmark_category(deserializer);
    var var_categoryTotalCount = sse_decode_u_16(deserializer);
    var var_categoryTotalSize = sse_decode_String(deserializer);
    return InternalCategoryStats(
      category: var_category,
      categoryTotalCount: var_categoryTotalCount,
      categoryTotalSize: var_categoryTotalSize,
    );
  }

  @protected
  InternalCustomDNS sse_decode_internal_custom_dns(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_usize(deserializer);
    var var_name = sse_decode_String(deserializer);
    return InternalCustomDNS(index: var_index, name: var_name);
  }

  @protected
  InternalCustomSourceDetails sse_decode_internal_custom_source_details(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_customSourceName = sse_decode_String(deserializer);
    var var_customSourceListings = sse_decode_list_String(deserializer);
    return InternalCustomSourceDetails(
      customSourceName: var_customSourceName,
      customSourceListings: var_customSourceListings,
    );
  }

  @protected
  InternalGlobalStats sse_decode_internal_global_stats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalTorrentsCount = sse_decode_u_32(deserializer);
    var var_totalTorrentsSize = sse_decode_String(deserializer);
    return InternalGlobalStats(
      totalTorrentsCount: var_totalTorrentsCount,
      totalTorrentsSize: var_totalTorrentsSize,
    );
  }

  @protected
  InternalPagination sse_decode_internal_pagination(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_previousPage = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_currentPage = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_nextPage = sse_decode_opt_box_autoadd_i_32(deserializer);
    return InternalPagination(
      previousPage: var_previousPage,
      currentPage: var_currentPage,
      nextPage: var_nextPage,
    );
  }

  @protected
  InternalProxy sse_decode_internal_proxy(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_32(deserializer);
    var var_proxyName = sse_decode_String(deserializer);
    var var_proxyType = sse_decode_String(deserializer);
    var var_proxyServerIp = sse_decode_String(deserializer);
    var var_proxyServerPort = sse_decode_String(deserializer);
    var var_proxyUsername = sse_decode_opt_String(deserializer);
    var var_proxyPassword = sse_decode_opt_String(deserializer);
    return InternalProxy(
      id: var_id,
      proxyName: var_proxyName,
      proxyType: var_proxyType,
      proxyServerIp: var_proxyServerIp,
      proxyServerPort: var_proxyServerPort,
      proxyUsername: var_proxyUsername,
      proxyPassword: var_proxyPassword,
    );
  }

  @protected
  InternalQueryOptions sse_decode_internal_query_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_categories = sse_decode_bool(deserializer);
    var var_filters = sse_decode_bool(deserializer);
    var var_sortings = sse_decode_bool(deserializer);
    var var_sortingOrders = sse_decode_bool(deserializer);
    var var_pagination = sse_decode_bool(deserializer);
    return InternalQueryOptions(
      categories: var_categories,
      filters: var_filters,
      sortings: var_sortings,
      sortingOrders: var_sortingOrders,
      pagination: var_pagination,
    );
  }

  @protected
  InternalSource sse_decode_internal_source(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourceName = sse_decode_String(deserializer);
    var var_sourceDetails = sse_decode_internal_source_details(deserializer);
    return InternalSource(
      sourceName: var_sourceName,
      sourceDetails: var_sourceDetails,
    );
  }

  @protected
  InternalSourceDetails sse_decode_internal_source_details(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_queryOptions = sse_decode_internal_query_options(deserializer);
    var var_categories = sse_decode_list_String(deserializer);
    var var_sourceFilters = sse_decode_list_String(deserializer);
    var var_sourceSortings = sse_decode_list_String(deserializer);
    var var_sourceSortingOrders = sse_decode_list_String(deserializer);
    return InternalSourceDetails(
      queryOptions: var_queryOptions,
      categories: var_categories,
      sourceFilters: var_sourceFilters,
      sourceSortings: var_sourceSortings,
      sourceSortingOrders: var_sourceSortingOrders,
    );
  }

  @protected
  InternalTorrent sse_decode_internal_torrent(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_infoHash = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_magnet = sse_decode_String(deserializer);
    var var_size = sse_decode_String(deserializer);
    var var_date = sse_decode_String(deserializer);
    var var_seeders = sse_decode_String(deserializer);
    var var_leechers = sse_decode_String(deserializer);
    var var_totalDownloads = sse_decode_String(deserializer);
    var var_sourceUrl = sse_decode_opt_String(deserializer);
    return InternalTorrent(
      infoHash: var_infoHash,
      name: var_name,
      magnet: var_magnet,
      size: var_size,
      date: var_date,
      seeders: var_seeders,
      leechers: var_leechers,
      totalDownloads: var_totalDownloads,
      sourceUrl: var_sourceUrl,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<InternalBookmarkCategory> sse_decode_list_internal_bookmark_category(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <InternalBookmarkCategory>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_internal_bookmark_category(deserializer));
    }
    return ans_;
  }

  @protected
  List<InternalCategoryStats> sse_decode_list_internal_category_stats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <InternalCategoryStats>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_internal_category_stats(deserializer));
    }
    return ans_;
  }

  @protected
  List<InternalCustomDNS> sse_decode_list_internal_custom_dns(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <InternalCustomDNS>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_internal_custom_dns(deserializer));
    }
    return ans_;
  }

  @protected
  List<InternalCustomSourceDetails>
  sse_decode_list_internal_custom_source_details(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <InternalCustomSourceDetails>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_internal_custom_source_details(deserializer));
    }
    return ans_;
  }

  @protected
  List<InternalSource> sse_decode_list_internal_source(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <InternalSource>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_internal_source(deserializer));
    }
    return ans_;
  }

  @protected
  List<InternalTorrent> sse_decode_list_internal_torrent(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <InternalTorrent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_internal_torrent(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(int, String)> sse_decode_list_record_i_32_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(int, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_i_32_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<(BigInt, String)> sse_decode_list_record_usize_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(BigInt, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_usize_string(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  InternalProxy? sse_decode_opt_box_autoadd_internal_proxy(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_internal_proxy(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (int, String) sse_decode_record_i_32_string(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_i_32(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (List<InternalTorrent>, InternalPagination)
  sse_decode_record_list_internal_torrent_internal_pagination(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_list_internal_torrent(deserializer);
    var var_field1 = sse_decode_internal_pagination(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (BigInt, String) sse_decode_record_usize_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_usize(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_Set_String_None(Set<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.toList(), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_internal_proxy(
    InternalProxy self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_internal_proxy(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_internal_torrent(
    InternalTorrent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_internal_torrent(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_i_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt8(self);
  }

  @protected
  void sse_encode_internal_bookmark_category(
    InternalBookmarkCategory self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.id, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_internal_bookmarks_stats(
    InternalBookmarksStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_internal_category_stats(self.categoriesStats, serializer);
    sse_encode_internal_global_stats(self.globalStats, serializer);
  }

  @protected
  void sse_encode_internal_category_stats(
    InternalCategoryStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_internal_bookmark_category(self.category, serializer);
    sse_encode_u_16(self.categoryTotalCount, serializer);
    sse_encode_String(self.categoryTotalSize, serializer);
  }

  @protected
  void sse_encode_internal_custom_dns(
    InternalCustomDNS self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.index, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_internal_custom_source_details(
    InternalCustomSourceDetails self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.customSourceName, serializer);
    sse_encode_list_String(self.customSourceListings, serializer);
  }

  @protected
  void sse_encode_internal_global_stats(
    InternalGlobalStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.totalTorrentsCount, serializer);
    sse_encode_String(self.totalTorrentsSize, serializer);
  }

  @protected
  void sse_encode_internal_pagination(
    InternalPagination self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_32(self.previousPage, serializer);
    sse_encode_opt_box_autoadd_i_32(self.currentPage, serializer);
    sse_encode_opt_box_autoadd_i_32(self.nextPage, serializer);
  }

  @protected
  void sse_encode_internal_proxy(InternalProxy self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.id, serializer);
    sse_encode_String(self.proxyName, serializer);
    sse_encode_String(self.proxyType, serializer);
    sse_encode_String(self.proxyServerIp, serializer);
    sse_encode_String(self.proxyServerPort, serializer);
    sse_encode_opt_String(self.proxyUsername, serializer);
    sse_encode_opt_String(self.proxyPassword, serializer);
  }

  @protected
  void sse_encode_internal_query_options(
    InternalQueryOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.categories, serializer);
    sse_encode_bool(self.filters, serializer);
    sse_encode_bool(self.sortings, serializer);
    sse_encode_bool(self.sortingOrders, serializer);
    sse_encode_bool(self.pagination, serializer);
  }

  @protected
  void sse_encode_internal_source(
    InternalSource self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sourceName, serializer);
    sse_encode_internal_source_details(self.sourceDetails, serializer);
  }

  @protected
  void sse_encode_internal_source_details(
    InternalSourceDetails self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_internal_query_options(self.queryOptions, serializer);
    sse_encode_list_String(self.categories, serializer);
    sse_encode_list_String(self.sourceFilters, serializer);
    sse_encode_list_String(self.sourceSortings, serializer);
    sse_encode_list_String(self.sourceSortingOrders, serializer);
  }

  @protected
  void sse_encode_internal_torrent(
    InternalTorrent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.infoHash, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.magnet, serializer);
    sse_encode_String(self.size, serializer);
    sse_encode_String(self.date, serializer);
    sse_encode_String(self.seeders, serializer);
    sse_encode_String(self.leechers, serializer);
    sse_encode_String(self.totalDownloads, serializer);
    sse_encode_opt_String(self.sourceUrl, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_internal_bookmark_category(
    List<InternalBookmarkCategory> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_internal_bookmark_category(item, serializer);
    }
  }

  @protected
  void sse_encode_list_internal_category_stats(
    List<InternalCategoryStats> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_internal_category_stats(item, serializer);
    }
  }

  @protected
  void sse_encode_list_internal_custom_dns(
    List<InternalCustomDNS> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_internal_custom_dns(item, serializer);
    }
  }

  @protected
  void sse_encode_list_internal_custom_source_details(
    List<InternalCustomSourceDetails> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_internal_custom_source_details(item, serializer);
    }
  }

  @protected
  void sse_encode_list_internal_source(
    List<InternalSource> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_internal_source(item, serializer);
    }
  }

  @protected
  void sse_encode_list_internal_torrent(
    List<InternalTorrent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_internal_torrent(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_i_32_string(
    List<(int, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_i_32_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_usize_string(
    List<(BigInt, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_usize_string(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_internal_proxy(
    InternalProxy? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_internal_proxy(self, serializer);
    }
  }

  @protected
  void sse_encode_record_i_32_string(
    (int, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_record_list_internal_torrent_internal_pagination(
    (List<InternalTorrent>, InternalPagination) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_internal_torrent(self.$1, serializer);
    sse_encode_internal_pagination(self.$2, serializer);
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_record_usize_string(
    (BigInt, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
