[package]
name = "libscrapper"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "test_bin"
path = "./src/testbin.rs"

[dependencies]
anyhow = "1.0.99"
html5ever = "0.35.0"
rand = "0.9.2"
reqwest = { version = "0.12.23" , features = ["blocking","json"]}
scraper = "0.23.1"