// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../internals.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<BigInt> bookmarkATorrent({
  required InternalTorrent torrent,
  required int categoryId,
}) => RustLib.instance.api.crateApiDatabaseBookmarkBookmarkATorrent(
  torrent: torrent,
  categoryId: categoryId,
);

Future<bool> removeBookmark({required String infoHash}) => RustLib.instance.api
    .crateApiDatabaseBookmarkRemoveBookmark(infoHash: infoHash);

Future<List<InternalTorrent>> getBookmarks({
  required int categoryId,
  required int limit,
  required int offset,
}) => RustLib.instance.api.crateApiDatabaseBookmarkGetBookmarks(
  categoryId: categoryId,
  limit: limit,
  offset: offset,
);

Future<Set<String>> getAllInfoHashes() =>
    RustLib.instance.api.crateApiDatabaseBookmarkGetAllInfoHashes();

Future<List<InternalBookmarkCategory>> getCategories() =>
    RustLib.instance.api.crateApiDatabaseBookmarkGetCategories();

Future<void> createBookmarkCategory({required String categoryName}) => RustLib
    .instance
    .api
    .crateApiDatabaseBookmarkCreateBookmarkCategory(categoryName: categoryName);

Future<void> renameBookmarkCategory({
  required int categoryId,
  required String oldCategoryName,
  required String newCategoryName,
}) => RustLib.instance.api.crateApiDatabaseBookmarkRenameBookmarkCategory(
  categoryId: categoryId,
  oldCategoryName: oldCategoryName,
  newCategoryName: newCategoryName,
);

Future<void> deleteBookmarkCategory({required int categoryId}) => RustLib
    .instance
    .api
    .crateApiDatabaseBookmarkDeleteBookmarkCategory(categoryId: categoryId);

Future<void> changeBookmarkCategory({
  required String infoHash,
  required int categoryId,
}) => RustLib.instance.api.crateApiDatabaseBookmarkChangeBookmarkCategory(
  infoHash: infoHash,
  categoryId: categoryId,
);

Future<List<InternalTorrent>> searchBookmarks({required String text}) =>
    RustLib.instance.api.crateApiDatabaseBookmarkSearchBookmarks(text: text);
