// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../internals.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_bookmark`, `get_bookmarks`

Future<BigInt> bookmarkATorrent({required InternalTorrent torrent}) => RustLib
    .instance
    .api
    .crateApiDatabaseBookmarkBookmarkATorrent(torrent: torrent);

Future<bool> removeBookmark({required String infoHash}) => RustLib.instance.api
    .crateApiDatabaseBookmarkRemoveBookmark(infoHash: infoHash);

Future<List<InternalTorrent>> getAllBookmarks() =>
    RustLib.instance.api.crateApiDatabaseBookmarkGetAllBookmarks();

Future<bool> checkBookmarkExistence({required String infoHash}) => RustLib
    .instance
    .api
    .crateApiDatabaseBookmarkCheckBookmarkExistence(infoHash: infoHash);
