// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String?> getASettingsKv({required String key}) =>
    RustLib.instance.api.crateApiDatabaseGetSettingsKvGetASettingsKv(key: key);

Future<String> insertOrUpdateKv({required String key, required String value}) =>
    RustLib.instance.api.crateApiDatabaseGetSettingsKvInsertOrUpdateKv(
      key: key,
      value: value,
    );

Future<Map<String, String>> getSettingsKv() =>
    RustLib.instance.api.crateApiDatabaseGetSettingsKvGetSettingsKv();

Future<BigInt> setDefaultTrackersList({required int index}) => RustLib
    .instance
    .api
    .crateApiDatabaseGetSettingsKvSetDefaultTrackersList(index: index);

Future<String> getActiveDefaultTrackersList() => RustLib.instance.api
    .crateApiDatabaseGetSettingsKvGetActiveDefaultTrackersList();
