// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../internals.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<(int, String)>> getSupportedProxyDetails() =>
    RustLib.instance.api.crateApiDatabaseProxyGetSupportedProxyDetails();

Future<BigInt> saveProxyApi({required InternalProxy proxyData}) => RustLib
    .instance
    .api
    .crateApiDatabaseProxySaveProxyApi(proxyData: proxyData);

Future<InternalProxy?> getSavedProxy() =>
    RustLib.instance.api.crateApiDatabaseProxyGetSavedProxy();

Future<BigInt> deleteProxy({required int proxyId}) =>
    RustLib.instance.api.crateApiDatabaseProxyDeleteProxy(proxyId: proxyId);
