// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'internals.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<InternalSource>> fetchSourceDetails() =>
    RustLib.instance.api.crateApiAppFetchSourceDetails();

Future<(List<InternalTorrent>, PlatformInt64?)> digTorrent({
  required String torrentName,
  required BigInt sourceIndex,
  required String category,
  required String filter,
  required String sorting,
  PlatformInt64? page,
}) => RustLib.instance.api.crateApiAppDigTorrent(
  torrentName: torrentName,
  sourceIndex: sourceIndex,
  category: category,
  filter: filter,
  sorting: sorting,
  page: page,
);

Future<InternalIpDetails> getIpDetails() =>
    RustLib.instance.api.crateApiAppGetIpDetails();

Future<int> checkNewUpdate() =>
    RustLib.instance.api.crateApiAppCheckNewUpdate();

Future<String> getAppCurrentVersion() =>
    RustLib.instance.api.crateApiAppGetAppCurrentVersion();

Future<List<(BigInt, String)>> getAllDefaultTrackersList() =>
    RustLib.instance.api.crateApiAppGetAllDefaultTrackersList();

Future<bool> loadDefaultTrackersString() =>
    RustLib.instance.api.crateApiAppLoadDefaultTrackersString();

Future<String> getProcessedMagnetLink({required String unprocessedMagnet}) =>
    RustLib.instance.api.crateApiAppGetProcessedMagnetLink(
      unprocessedMagnet: unprocessedMagnet,
    );

Future<List<String>> getCustomsDetails() =>
    RustLib.instance.api.crateApiAppGetCustomsDetails();

Future<(List<InternalTorrent>, PlatformInt64?)> digCustomTorrents({
  required BigInt index,
}) => RustLib.instance.api.crateApiAppDigCustomTorrents(index: index);
