// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class InternalQueryOptions {
  final bool categories;
  final bool sortings;
  final bool filters;

  const InternalQueryOptions({
    required this.categories,
    required this.sortings,
    required this.filters,
  });

  @override
  int get hashCode =>
      categories.hashCode ^ sortings.hashCode ^ filters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InternalQueryOptions &&
          runtimeType == other.runtimeType &&
          categories == other.categories &&
          sortings == other.sortings &&
          filters == other.filters;
}

class InternalSourceDetails {
  final InternalQueryOptions queryOptions;
  final List<String> categories;
  final List<String> sourceFilters;
  final List<String> sourceSortings;

  const InternalSourceDetails({
    required this.queryOptions,
    required this.categories,
    required this.sourceFilters,
    required this.sourceSortings,
  });

  @override
  int get hashCode =>
      queryOptions.hashCode ^
      categories.hashCode ^
      sourceFilters.hashCode ^
      sourceSortings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InternalSourceDetails &&
          runtimeType == other.runtimeType &&
          queryOptions == other.queryOptions &&
          categories == other.categories &&
          sourceFilters == other.sourceFilters &&
          sourceSortings == other.sourceSortings;
}

class InternalTorrent {
  final String infoHash;
  final String name;
  final String magnet;
  final String size;
  final String date;
  final String seeders;
  final String leechers;
  final String totalDownloads;

  const InternalTorrent({
    required this.infoHash,
    required this.name,
    required this.magnet,
    required this.size,
    required this.date,
    required this.seeders,
    required this.leechers,
    required this.totalDownloads,
  });

  @override
  int get hashCode =>
      infoHash.hashCode ^
      name.hashCode ^
      magnet.hashCode ^
      size.hashCode ^
      date.hashCode ^
      seeders.hashCode ^
      leechers.hashCode ^
      totalDownloads.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InternalTorrent &&
          runtimeType == other.runtimeType &&
          infoHash == other.infoHash &&
          name == other.name &&
          magnet == other.magnet &&
          size == other.size &&
          date == other.date &&
          seeders == other.seeders &&
          leechers == other.leechers &&
          totalDownloads == other.totalDownloads;
}
