// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class InternalCustomSourceDetails {
  final String customSourceName;
  final List<String> customSourceListings;

  const InternalCustomSourceDetails({
    required this.customSourceName,
    required this.customSourceListings,
  });

  @override
  int get hashCode => customSourceName.hashCode ^ customSourceListings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InternalCustomSourceDetails &&
          runtimeType == other.runtimeType &&
          customSourceName == other.customSourceName &&
          customSourceListings == other.customSourceListings;
}

class InternalProxy {
  final int id;
  final String proxyName;
  final String proxyType;
  final String proxyServerIp;
  final String proxyServerPort;
  final String? proxyUsername;
  final String? proxyPassword;

  const InternalProxy({
    required this.id,
    required this.proxyName,
    required this.proxyType,
    required this.proxyServerIp,
    required this.proxyServerPort,
    this.proxyUsername,
    this.proxyPassword,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      proxyName.hashCode ^
      proxyType.hashCode ^
      proxyServerIp.hashCode ^
      proxyServerPort.hashCode ^
      proxyUsername.hashCode ^
      proxyPassword.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InternalProxy &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          proxyName == other.proxyName &&
          proxyType == other.proxyType &&
          proxyServerIp == other.proxyServerIp &&
          proxyServerPort == other.proxyServerPort &&
          proxyUsername == other.proxyUsername &&
          proxyPassword == other.proxyPassword;
}

class InternalQueryOptions {
  final bool categories;
  final bool filters;
  final bool sortings;
  final bool sortingOrders;
  final bool pagination;

  const InternalQueryOptions({
    required this.categories,
    required this.filters,
    required this.sortings,
    required this.sortingOrders,
    required this.pagination,
  });

  @override
  int get hashCode =>
      categories.hashCode ^
      filters.hashCode ^
      sortings.hashCode ^
      sortingOrders.hashCode ^
      pagination.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InternalQueryOptions &&
          runtimeType == other.runtimeType &&
          categories == other.categories &&
          filters == other.filters &&
          sortings == other.sortings &&
          sortingOrders == other.sortingOrders &&
          pagination == other.pagination;
}

class InternalSource {
  final String sourceName;
  final InternalSourceDetails sourceDetails;

  const InternalSource({required this.sourceName, required this.sourceDetails});

  @override
  int get hashCode => sourceName.hashCode ^ sourceDetails.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InternalSource &&
          runtimeType == other.runtimeType &&
          sourceName == other.sourceName &&
          sourceDetails == other.sourceDetails;
}

class InternalSourceDetails {
  final InternalQueryOptions queryOptions;
  final List<String> categories;
  final List<String> sourceFilters;
  final List<String> sourceSortings;
  final List<String> sourceSortingOrders;

  const InternalSourceDetails({
    required this.queryOptions,
    required this.categories,
    required this.sourceFilters,
    required this.sourceSortings,
    required this.sourceSortingOrders,
  });

  @override
  int get hashCode =>
      queryOptions.hashCode ^
      categories.hashCode ^
      sourceFilters.hashCode ^
      sourceSortings.hashCode ^
      sourceSortingOrders.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InternalSourceDetails &&
          runtimeType == other.runtimeType &&
          queryOptions == other.queryOptions &&
          categories == other.categories &&
          sourceFilters == other.sourceFilters &&
          sourceSortings == other.sourceSortings &&
          sourceSortingOrders == other.sourceSortingOrders;
}

class InternalTorrent {
  final String infoHash;
  final String name;
  final String magnet;
  final String size;
  final String date;
  final String seeders;
  final String leechers;
  final String totalDownloads;

  const InternalTorrent({
    required this.infoHash,
    required this.name,
    required this.magnet,
    required this.size,
    required this.date,
    required this.seeders,
    required this.leechers,
    required this.totalDownloads,
  });

  @override
  int get hashCode =>
      infoHash.hashCode ^
      name.hashCode ^
      magnet.hashCode ^
      size.hashCode ^
      date.hashCode ^
      seeders.hashCode ^
      leechers.hashCode ^
      totalDownloads.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InternalTorrent &&
          runtimeType == other.runtimeType &&
          infoHash == other.infoHash &&
          name == other.name &&
          magnet == other.magnet &&
          size == other.size &&
          date == other.date &&
          seeders == other.seeders &&
          leechers == other.leechers &&
          totalDownloads == other.totalDownloads;
}
